version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.9-stretch-node
      - image: circleci/mysql:latest
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true 
          MYSQL_DATABASE: tbox 
          MYSQL_HOST: 127.0.0.1 
          MYSQL_ROOT_HOST: root
          MYSQL_USER: root

    working_directory: /go/src/github.com/leowilbur/tbox

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            go get -v github.com/onsi/ginkgo/ginkgo           
            go get -u -d github.com/golang-migrate/migrate/cli
            cd $GOPATH/src/github.com/golang-migrate/migrate/cli
            go build -tags 'mysql' -o $GOPATH/bin/migrate github.com/golang-migrate/migrate/cli

      - save_cache:
          paths:
            - node_modules
            - /home/circleci/go/bin
          key: dependencies
    
      - run: 
          name: Run unit tests with ginkgo
          command: |
            ginkgo -r -skipPackage=vendor --randomizeSuites --failOnPending --cover --trace --race --progress
      